2025-01-29 14:11:48.704959: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "miner.py", line 367, in <module>
    base_model = make_base()
  File "miner.py", line 127, in make_base
    model['accuracy'] = worker.evaluate()
  File "C:\Users\xiaoming\Desktop\BlockchainForFederatedLearning-master\cifar\federatedlearner.py", line 168, in evaluate
    self.Y: self.test_y
  File "D:\anaconda\envs\BlockchainForFederatedLearning\lib\site-packages\tensorflow\python\client\session.py", line 887, in run
    run_metadata_pt r)
  File "D:\anaconda\envs\BlockchainForFederatedLearning\lib\site-packages\tensorflow\python\client\session.py", line 1086, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape () for Tensor 'X:0', which has shape '(?, 32, 32, 3)'
